services:
  frontend:
    image: myacrvitetest.azurecr.io/test-image:test
    ports:
      - "3000:80"  
    networks:
      - app-network
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCOPE=frontend
      - REGISTRY_USER= 
      - REGISTRY_PASSWORD= 
      - REGISTRY_TENANT= 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
