name: Pull Docker Image from Azure ACR

on:
  workflow_dispatch: # Allows you to trigger this workflow manually
  push:
    branches:
      - main

jobs:
  pull-docker-image:
    runs-on: self-hosted # Use your self-hosted runner

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Pull the Docker image
      - name: Pull Docker Image from ACR
        run: |
          docker pull ${{ secrets.ACR_NAME }}.azurecr.io/test-image:dev

      # Run the Docker container
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:80 --name test-container ${{ secrets.ACR_NAME }}.azurecr.io/test-image:dev